
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
  creationTimestamp: null
  name: buckets.ab.leclouddev.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.cloud
    name: Cloud
    type: string
  - JSONPath: .spec.fullName
    name: FullName
    type: string
  - JSONPath: .status.createdAt
    name: CreatedAt
    type: string
  group: ab.leclouddev.com
  names:
    kind: Bucket
    listKind: BucketList
    plural: buckets
    singular: bucket
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Bucket is the Schema for the buckets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: BucketSpec defines the desired state of Bucket
          properties:
            cloud:
              description: Cloud platform
              enum:
              - gcp
              type: string
            fullName:
              description: FullName is the cloud storage bucket full name
              type: string
            onDeletePolicy:
              description: OnDeletePolicy defines the behavior when the Deployment/Bucket
                objects are deleted
              enum:
              - destroy
              - ignore
              type: string
          required:
          - cloud
          - fullName
          - onDeletePolicy
          type: object
        status:
          description: BucketStatus defines the observed state of Bucket
          properties:
            createdAt:
              description: CreatedAt is the cloud storage bucket creation time
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
